import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "About Page",
//   description: "Generated by About page",
// };
//metadata inside page will override the metadata in root layout / layout.tsx
// metadata is shallow copied.

// only if need to dynamically generate metadata
// takes params and search params
export async function generateMetadata({
  params,
}: {
  params: { id: string };
}): Promise<Metadata> {
  return {
    title: `About ${params.id}`,
    description: `About ${params.id}`,
  };
}

export default function About() {
  return <div>About</div>;
}
